name: WebdriverIO CI

on:
  push:
    branches:
      - Feature_Nov23
  pull_request:
    branches:
      - Feature_Nov23

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.16.0 # Use the Node.js version your framework supports

    - name: Install dependencies
      run: npm install

    - name: Run WebdriverIO tests
      run: npm run wdio
      env:
        CI: true

    - name: Upload Allure Results
      if: success()  # Upload only if the tests pass
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results/

    - name: Generate Allure Report
      if: success()  # Generate report only on success
      run: |
        npm run allure:generate
        npm run allure:open
